{% set name = "spider-crawler" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .  # This means the recipe is in the same directory as the source

build:
  noarch: python
  number: 0
  script: |
    {{ PYTHON }} -m pip install . -vv
    {{ PYTHON }} -m pip install selenium-stealth>=1.0.6 undetected-chromedriver>=3.4.6

  entry_points:
    - spider = spider.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - selenium >=4.1.0
    - beautifulsoup4 >=4.10.0
    - html2text >=2020.1.16
    - webdriver-manager >=3.5.2

test:
  imports:
    - spider
  commands:
    - spider --help
    # Verify pip packages were installed properly
    - {{ PYTHON }} -c "import selenium_stealth"
    - {{ PYTHON }} -c "import undetected_chromedriver"

about:
  home: https://github.com/melliott-anaconda/spider-crawler
  license: MIT
  license_file: LICENSE
  summary: A flexible web crawler for keyword searching and content extraction
  description: |
    Spider is a web crawler that can search websites for keywords 
    or save content as markdown. It features adaptive rate control,
    checkpoint/resume functionality, and support for Single Page Applications.
  doc_url: https://github.com/melliott-anaconda/spider-crawler
  dev_url: https://github.com/melliott-anaconda/spider-crawler

extra:
  recipe-maintainers:
    - melliott-anaconda